# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: attenza-ingress
#   namespace: attenza
# spec:
#   tls:
#     - hosts:
#         - attenza.bijaymsra.site
#       secretName: attenza-tls
#   rules:
#     - host: attenza.bijaymsra.site
#       http:
#         paths:
#           - path: /api
#             pathType: Prefix
#             backend:
#               service:
#                 name: backend
#                 port:
#                   number: 8080
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend
#                 port:
#                   number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attenza-ingress
  namespace: attenza
spec:
  rules:
    - host: attenza.bijaymsra.site
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80