apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attenza-ingress
  namespace: attenza
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - bijaymsra.site
      secretName: attenza-tls
  rules:
    - host: bijaymsra.site
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
