apiVersion: v1
kind: Secret
metadata:
  name: attenza-secret
  namespace: attenza
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysql:3306/attenza_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  DB_USERNAME: attenza_user
  DB_PASSWORD: attenza_pass
  MAIL_USERNAME: 3techsoul@gmail.com
  MAIL_PASSWORD: azwp pavd xans jicw
  QR_SECRET: A7xQpN9mZC8eFJ3K2R0dS1B4H6V5LWyT
  QR_VALIDITY_SECONDS: "30"