apiVersion: v1
kind: Secret
metadata:
  name: attenza-secret
  namespace: attenza
type: Opaque
stringData:
  # -------------------------------
  # MySQL Configuration
  # -------------------------------
  MYSQL_ROOT_PASSWORD: change_me_root_password
  MYSQL_DATABASE: your_database_name
  MYSQL_USER: your_database_user
  MYSQL_PASSWORD: your_database_password

  # -------------------------------
  # Spring Boot DB Configuration
  # -------------------------------
  DB_URL: jdbc:mysql://mysql:3306/your_database_name?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  DB_USERNAME: your_database_user
  DB_PASSWORD: your_database_password

  # -------------------------------
  # Mail Configuration
  # -------------------------------
  MAIL_USERNAME: your_email@example.com
  MAIL_PASSWORD: your_app_specific_password

  # -------------------------------
  # QR Security Configuration
  # -------------------------------
  QR_SECRET: replace_with_secure_random_string
  QR_VALIDITY_SECONDS: "30"
