apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: attenza
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: attenza_db
  MYSQL_USER: attenza_user
  MYSQL_PASSWORD: attenza_pass
