server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: attenza-backend
  
  # LOCAL MySQL Config (uncomment when using local MySQL)
  # datasource:
  #   url: jdbc:mysql://localhost:3306/attenza_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #   username: attenza_user
  #   password: attenza_pass
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  
  # DOCKER MySQL Config (uncomment when using Docker)
  datasource: 
    url: jdbc:mysql://localhost:3306/attenza_db
    username: attenza_user
    password: attenza_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  # datasource:
  #   url: jdbc:mysql://mysql:3306/attenza_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #   username: attenza_user
  #   password: attenza_pass
  #   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 3techsoul@gmail.com
    password: nhuo tblu egzf jino
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


attendance:
  qr:
    secret: "A7xQpN9mZC8eFJ3K2R0dS1B4H6V5LWyT"
    validity-seconds: 30


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true